### ISSUE TITLE
How would you despawn the root after root.spawn()? 

### ISSUE THREAD

**Issue by simply-created** [septum/bevy_ui_bits#1]
I am trying to despawn the root for transitioning the loading screen to a main menu screen.

**Comment by septum** [comment]
You could do something like this:

```rust
// Trying to be specific here instead of using `*`
use bevy_ui_bits::RootMarker;

// ...

fn despawn_root(mut commands: Commands, root_query: Query<Entity, With<RootMarker>>) {
    let entity = root_query.single();
    commands.entity(entity).despawn_recursive();
}
```

As the name implies, `RootMarker` is a marker component that is inserted in every `Root`. Here's the line where that happens: 
- https://github.com/septum/bevy_ui_bits/blob/main/src/layout/root.rs#L66

Hope that helps!
